"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
# https://pypi.org/project/environs/#install
from environs import env  

env.read_env()       # read .env file, if it exists


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# SECRET_KEY = 'django-insecure-x)2bgp+xrht7$i2-zb#!*siv8(c@yigqq)g(2g=njvdg)v8fic'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    # Build-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # required for serving swagger ui's css/js files
    
    # My local apps
    'users.apps.UsersConfig',
    'property.apps.PropertyConfig',
    
    # Third party apps
    # -----------------
    # https://django-phonenumber-field.readthedocs.io/en/latest/#
    'phonenumber_field',
    # https://www.django-rest-framework.org/
    'rest_framework',
    # https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html
    'rest_framework_simplejwt',   # djangorestframework-simplejwt
    'rest_framework_simplejwt.token_blacklist',
    # https://pypi.org/project/django-cors-headers/
    'corsheaders',
      
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # https://pypi.org/project/django-cors-headers/
    'corsheaders.middleware.CorsMiddleware',    #'corsheaders',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases





DATABASES = {
    # Development
    # 'default': {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }

    # DEVELOPMENT
    'default': {
        'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
        'NAME'    : os.getenv('DB_NAME'),
        'USER'    : os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST'    : os.getenv('DB_HOST'),
        'PORT'    : os.getenv('DB_PORT'),
    }
    
 #PRODUCTION
    # 'default': dj_database_url.config(
    #     default=os.getenv('DATABASE_URL'), 
    #     conn_max_age=600    
    #     )
}






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


## Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC
STATIC_URL = 'static/'
# MEDIA
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD ='django.db.models.BigAutoField'
AUTH_USER_MODEL='users.CustomUser'


#  Email 
# DEFAULT_FROM_EMAIL='developer.web.dj@gmail.com'
DEFAULT_FROM_EMAIL = 'noreply@mywebsite'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'







REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #  normal JWTAuthentication
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        
        # my customize JWTAuthentication useing cookie
        'users.authentication.CookieCustomJWTAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
  
}




# https://github.com/jazzband/djangorestframework-simplejwt
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}








# https://pypi.org/project/django-cors-headers/
CORS_ALLOW_ALL_ORIGINS = True  # or use CORS_ALLOWED_ORIGINS = [...]
CORS_ALLOW_CREDENTIALS = True  # Enable cookie/session support across domains




# Required if using cookies  // Django settings should allow cookies from localhost:3000
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

FRONTEND_DOMAIN = "localhost:3000"  # or your actual frontend domain


# If using SessionAuthentication or JWT in cookie:
# CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]
# SESSION_COOKIE_SAMESITE = "None"  # or "None" if cross-domain and using HTTPS
# SESSION_COOKIE_SECURE = True    # True if using HTTPS
