# Generated by Django 5.2.4 on 2025-09-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypurpose',
            old_name='purpose_sub_choice_name',
            new_name='purpose_name',
        ),
    ]
