# Generated by Django 5.2.4 on 2025-09-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='pmain_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertymaintype'),
        ),
        migrations.AddField(
            model_name='propertypurposesubchoices',
            name='main_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose_choices', to='property.propertymaintype'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertypurposesubchoices'),
        ),
        migrations.AddField(
            model_name='propertysubtypes',
            name='main_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='property.propertymaintype'),
        ),
        migrations.AddField(
            model_name='property',
            name='psub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertysubtypes'),
        ),
    ]
