# Generated by Django 5.2.4 on 2025-10-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypurpose',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
