# Generated by Django 5.2.4 on 2025-09-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_purpose_sub_choice_name_propertypurpose_purpose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypurpose',
            name='purpose_name',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='propertypurpose',
            unique_together={('purpose_name', 'main_type')},
        ),
    ]
