# Generated by Django 5.2.4 on 2025-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertypurpose_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypurpose',
            old_name='slug',
            new_name='purpose_slug',
        ),
        migrations.AlterField(
            model_name='propertypurpose',
            name='purpose_name',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=100, unique=True),
        ),
    ]
