# Generated by Django 5.2.4 on 2025-10-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertypurpose_purpose_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertypurpose',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='propertypurpose',
            name='purpose_name',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='propertypurpose',
            name='main_type',
        ),
    ]
