# Generated by Django 5.2.4 on 2025-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_slug_propertypurpose_purpose_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymaintype',
            name='maintype_slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
