# Generated by Django 5.2.4 on 2025-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertymaintype_maintype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymaintype',
            name='maintype_name',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertymaintype',
            name='maintype_slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
