# Generated by Django 5.2.4 on 2026-05-16 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nproj_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('nproj_main_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use')], max_length=225, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('full_area', models.DecimalField(decimal_places=2, help_text='Size in sqm', max_digits=10)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True)),
                ('hand_over_year', models.DateField(blank=True, null=True)),
                ('hand_over_year_quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=20, null=True)),
                ('status_detail', models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('off_plan', 'Off Plan'), ('completed', 'Completed'), ('handed_over', 'Handed Over'), ('launching_soon', 'Launching Soon')], max_length=20, null=True)),
                ('lunch_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='property.amenity')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
