# Generated by Django 5.2.4 on 2026-05-17 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_newproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='new_project_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('new_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_project_images', to='property.newproject')),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='new_project_videos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('new_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_project_videos', to='property.newproject')),
            ],
        ),
    ]
