# Generated by Django 5.2.4 on 2026-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_newprojectimage_newprojectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='nproj_main_type_slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='amenities',
            field=models.ManyToManyField(null=True, to='property.amenity'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='nproj_main_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use')], max_length=225, null=True),
        ),
    ]
