# Generated by Django 5.2.4 on 2026-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_newproject_nproj_main_type_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='nproj_main_type_slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='nproj_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
