# Generated by Django 5.2.4 on 2026-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_newproject_nproj_main_type_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='hand_over_year_quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=20, null=True),
        ),
    ]
