# Generated by Django 5.2.4 on 2026-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_newproject_hand_over_year_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprojectvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/%Y/%m/%d/'),
        ),
    ]
