# Generated by Django 5.2.4 on 2026-05-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_newprojectvideo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newprojectvideo',
            old_name='video',
            new_name='videos',
        ),
    ]
