# Generated by Django 5.2.4 on 2026-05-21 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_video_newprojectvideo_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('new_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_project_documents', to='property.newproject')),
            ],
        ),
    ]
