# Generated by Django 5.2.4 on 2026-05-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_newprojectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprojectimage',
            name='images',
            field=models.ImageField(blank=True, default='default_images/default_image.jpg', null=True, upload_to='new_project_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newprojectvideo',
            name='videos',
            field=models.FileField(blank=True, default='default_images/default_video.jpg', null=True, upload_to='project_videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='images',
            field=models.ImageField(blank=True, default='default_images/default_image.jpg', null=True, upload_to='property_images/%Y/%m/%d/'),
        ),
    ]
