// src/app/layout.tsx
"use client"

import './globals.css'; // ✅ THIS LINE IS IMPORTANT
import { Poetsen_One } from "next/font/google";

import { usePathname } from "next/navigation";
import { AuthProvider } from './context/AuthContext';
import Navbar from './components/navbar/Navbar';

// src/app/layout.tsx
// import "react-toastify/dist/ReactToastify.css";
// import { ToastContainer } from "react-toastify";

// import LoginModal from "./components/modals/LoginModal";
// import SearchModal from "./components/modals/SearchModal";
// import SignupModal from "./components/modals/SignupModal";
// import AddPropertyModal from "./components/modals/AddPropertyModal";


// google font 
const poetsenOne = Poetsen_One(
  {  weight: '400',
    subsets: ["latin"] 
  }
);

export const Metadata = {
  title:       "DjangoBnb",
  description: "Generated by create next app",
};


// src/app/layout.js
export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();
    
    
    const hideNavbar = 
      pathname === "/login" ||
      // pathname === "/register/buyer" || 
      pathname === "/forgotPassword" ||
      pathname === "/noteCheckEmail" ||
      pathname === "/notePasswordResetComplete" ||
      pathname === "/changePassword" ||
      pathname.startsWith("/setNewPassword/") ||      // for the dynamic path "/setNewPassword/[uid]/[token]"
      pathname.startsWith("/users/confirm-email/") ||  // for the dynamic path "/users/confirm-email/[uid]/[token]"
      pathname.startsWith("/register")              // for the dynamic path "/register/[role]"
      
      // console.log("/users/confirm-email/", pathname.startsWith("/users/confirm-email/"))
    
    
    
      return (

      <html lang="en">
        <body className={poetsenOne.className}>

          <AuthProvider>
              {!hideNavbar && <Navbar />}
              <div>
                <main>
                  {children}
                  {/* <ToastContainer position="top-center" autoClose={3000} /> */}
                </main>
              </div>
          </AuthProvider>
        
        </body>
      </html>
    );
}